[project]
name = "Decoding-Explorer"
version = "0.1.0"
description = "Our application is a powerful and intuitive tool designed for researchers and scientists in the field of single-cell proteomics. It allows users to load, visualize, and analyze protein distribution at the single-cell level. By providing a user-friendly interface, the app enables seamless exploration of protein expression data, helping to uncover insights into cellular functions, interactions, and heterogeneity."
readme = "README.md"
requires-python = ">=3.10.16,<=3.10.18"
dependencies = [
   "astroalign==2.6.1",
    "diplib==3.5.2",
    "marsilea==0.5.6",
    "matplotlib==3.10.3",
    "numexpr==2.11.0",
    "numpy==1.26.4",
    "opencv-contrib-python==4.11.0.86",
    "pandas==2.3.0",
    "pillow==11.3.0",
    "plotly==6.2.0",
    "psutil==7.0.0",
    "pyclesperanto==0.18.3",
    "pyqt6==6.9.1",
    "pyqt6-qt6==6.9.1",
    "pyqt6-sip==13.10.2",
    "pyqtgraph==0.13.7",
    "pystackreg==0.2.8",
    "qtrangeslider==0.1.5",
    "scanpy[leiden]==1.11.5",
    "scikit-image==0.24.0",
    "scikit-learn==1.7.2",
    "scipy==1.15.3",
    "seaborn==0.13.2",
    "simpleitk==2.5.2",
    "sklearn-ann==0.1.4",
    "stardist>=0.9.1",
    "tensorflow==2.8.0; platform_machine == 'AMD64'",
    "protobuf==3.20.0; platform_machine == 'AMD64'",
    "tensorflow-cpu==2.8.0; platform_machine == 'AMD64'",
    "tensorflow==2.16.2; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "tensorflow-macos==2.16.2; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "tensorflow-metal==1.1.0; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "tifffile==2025.5.10",
    "tqdm==4.67.1",
    "centrosome>=1.3.3",
    "openpyxl>=3.1.5",
]

[project.optional-dependencies]
test = [
    "pytest==8.4.1",
    "pytest-cov==6.2.1",
    "pytest-qt==4.5.0",
]
build = [
    "pyinstaller>=6.18.0",
]
notebook = [
    "ipykernel==6.29.5",
    "ipython==8.37.0",
    "ipywidgets==8.1.7",
    "jupyter==1.1.1",
    "jupyterlab==4.4.7",
    "notebook==7.4.5",
]
[tool.uv.sources]
stardist = { git = "https://github.com/mingl1/stardist.git", rev = "44b598cdee601156b45eacaab50c3928516b9a00" }

[tool.uv]
required-environments = [
    "sys_platform == 'win32'"
]
override-dependencies = [
    "tensorflow-io-gcs-filesystem; platform_machine == 'AMD64'",
]

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true # This forces the agent to use type hints

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
qt_api = "pyqt6"
python_files = "test_*.py"
